datasheet_url = "https://www.winbond.com/resource-files/w25q32jv%20revh%2001072019%20plus.pdf"
datasheet_link_url = "https://www.winbond.com/hq/product/code-storage-flash-memory/serial-nor-flash/?__locale=en&selected=32Mb#Density"
