datasheet_url = "https://www.winbond.com/resource-files/w25q80dv%20dl_revh_10022015.pdf"
datasheet_link_url = "https://www.winbond.com/hq/product/code-storage-flash-memory/serial-nor-flash/?__locale=en&selected=8Mb#Density"
