datasheet_url = "https://www.winbond.com/resource-files/w25q16jv_dtr%20reve%2002092018%20plus.pdf"
datasheet_link_url = "https://www.winbond.com/hq/product/code-storage-flash-memory/serial-nor-flash/?__locale=en&selected=16Mb#Density"
