datasheet_url = "https://www.winbond.com/resource-files/w25q64jv%20revj%2003272018%20plus.pdf"
datasheet_link_url = "https://www.winbond.com/hq/product/code-storage-flash-memory/serial-nor-flash/?__locale=en&selected=64Mb#Density"
