datasheet_url = "https://www.winbond.com/resource-files/w25q128jv%20revg%2004082019%20plus.pdf"
datasheet_link_url = "https://www.winbond.com/hq/product/code-storage-flash-memory/serial-nor-flash/?__locale=en&selected=128Mb#Density"
