datasheet_url = "https://www.winbond.com/resource-files/w25q64fv%20revs%2007182017.pdf"
datasheet_link_url = "https://www.winbond.com/hq/product/code-storage-flash-memory/serial-nor-flash/?__locale=en&selected=64Mb#Density"
