datasheet_url = "https://www.winbond.com/resource-files/w25q16fw%20revk%2003292019%20sfdp%20.pdf"
datasheet_link_url = "https://www.winbond.com/hq/product/code-storage-flash-memory/serial-nor-flash/?__locale=en&selected=16Mb#Density"
